### ISSUE TITLE
Release to Hex

### ISSUE THREAD

**Issue by tdcain89** [tdcain89/ftpoison#2]
Would like to release this to Hex so that others can benefit. Below is the list of things I'd like to accomplish before doing so:

# TODO
- [ ] Write tests
- [ ] Finish writing moduledocs/docs
- [ ] Write a real README
- [ ] Bump elixir version
- [ ] Think about some kind of CI/Credo CI
